let initialCards = [
    {
        id: 6,
        name: 'Карандаши цветные Faber-Castell "Замок, набор 24 цвета, заточенные, шестигранные, Faber-Castell',
        color: "белый",
        size: "",
        storage: "Коледино WB",
        seller: "OOO Вайлдберриз",
        image: "https://github.com/Pavel-174/WB-L0/blob/main/src/images/Frame277132128.jpg?raw=true",
        price: 494,
        fullPrice: 950,
        quantity: 0,
        buyQuantity: 0,
        checked: false,
        deliveryDate: '',
        deliveryDate2: '',
        deliveryQuantity: '',
        deliveryQuantity2: '',
        totalPrice: "",
        totalFullPrice: '',
    },
    {
        id: 5,
        name: "Силиконовый чехол картхолдер (отверстия) для карт, прозрачный кейс бампер на Apple iPhone XR, MobiSafe",
        color: "прозрачный",
        size: "",
        storage: "Коледино WB",
        seller: "OOO Мегапрофстиль",
        image: "https://github.com/Pavel-174/WB-L0/blob/main/src/images/Frame277132129.jpg?raw=true",
        price: 10500.235,
        fullPrice: 2300047,
        quantity: 0,
        buyQuantity: 0,
        checked: false,
        deliveryDate: '',
        deliveryDate2: '',
        deliveryQuantity: '',
        deliveryQuantity2: '',
        totalPrice: "",
        totalFullPrice: '',
    },
    {
        id: 4,
        name: "Футболка UZcotton мужская",
        color: "белый",
        size: "56",
        storage: "Коледино WB",
        seller: "OOO Вайлдберриз",
        image: "https://github.com/Pavel-174/WB-L0/blob/main/src/images/Frame3853.jpg?raw=true",
        price: 522,
        fullPrice: 1051,
        quantity: 0,
        buyQuantity: 0,
        checked: false,
        deliveryDate: '',
        deliveryDate2: '',
        deliveryQuantity: '',
        deliveryQuantity2: '',
        totalPrice: "",
        totalFullPrice: '',
    },
    {
        id: 3,
        name: "Футболка UZcotton мужская",
        color: "белый",
        size: "56",
        storage: "Коледино WB",
        seller: "OOO Вайлдберриз",
        image: "https://github.com/Pavel-174/WB-L0/blob/main/src/images/Frame3853.jpg?raw=true",
        price: 522,
        fullPrice: 1051,
        quantity: 2,
        buyQuantity: 2,
        checked: true,
        deliveryDate: '5—6 февраля',
        deliveryDate2: '',
        deliveryQuantity: 2,
        deliveryQuantity2: '',
        totalPrice: "",
        totalFullPrice: '',
    },
    {
        id: 2,
        name: "Силиконовый чехол картхолдер (отверстия) для карт, прозрачный кейс бампер на Apple iPhone XR, MobiSafe",
        color: "прозрачный",
        size: "",
        storage: "Коледино WB",
        seller: "OOO Мегапрофстиль",
        image: "https://github.com/Pavel-174/WB-L0/blob/main/src/images/Frame277132129.jpg?raw=true",
        price: 10500,
        fullPrice: 2300047,
        quantity: 201,
        buyQuantity: 200,
        checked: true,
        deliveryDate: '5—6 февраля',
        deliveryDate2: '6—7 февраля',
        deliveryQuantity: 184,
        deliveryQuantity2: 16,
        totalPrice: "",
        totalFullPrice: '',
    },
    {
        id: 1,
        name: 'Карандаши цветные Faber-Castell "Замок, набор 24 цвета, заточенные, шестигранные, Faber-Castell',
        color: "белый",
        size: "",
        storage: "Коледино WB",
        seller: "OOO Вайлдберриз",
        image: "https://github.com/Pavel-174/WB-L0/blob/main/src/images/Frame277132128.jpg?raw=true",
        price: 247,
        fullPrice: 950,
        quantity: 1,
        buyQuantity: 1,
        checked: true,
        deliveryDate: '5—6 февраля',
        deliveryDate2: '',
        deliveryQuantity: '1',
        deliveryQuantity2: '',
        totalPrice: "",
        totalFullPrice: '',
    },
]


export {initialCards}
