const initialCards = [
    {
        id: 3,
        name: "Футболка UZcotton мужская",
        color: "белый",
        size: "56",
        storage: "Коледино WB",
        seller: "OOO Вайлдберриз",
        image: "./images/Frame3853.jpg",
        price: "522",
        quantity: 2,
        buyQuantity: 1,
    },
    {
        id: 2,
        name: "Силиконовый чехол картхолдер (отверстия) для карт, прозрачный кейс бампер на Apple iPhone XR, MobiSafe",
        color: "прозрачный",
        size: "",
        storage: "Коледино WB",
        seller: "OOO Мегапрофстиль",
        image: "./images/Frame277132129.jpg",
        price: "2 100 047",
        quantity: "201",
        buyQuantity: 200,
    },
    {
        id: 1,
        name: 'Карандаши цветные Faber-Castell "Замок, набор 24 цвета, заточенные, шестигранные, Faber-Castell',
        color: "белый",
        size: "",
        storage: "Коледино WB",
        seller: "OOO Вайлдберриз",
        image: "./images/Frame277132128.jpg",
        price: "494",
        quantity: 1,
        buyQuantity: 1,
    },
]