const cards = [
    {
        id: 1,
        name: "Футболка UZcotton мужская",
        color: "белый",
        size: "56",
        storage: "Коледино WB",
        seller: "OOO Вайлдберриз",
        image: "./images/Frame3853.jpg",
        price: "522",
        quantity: "2",
    },
    {
        id: 2,
        name: "Футболка UZcotton мужская",
        color: "",
        size: "56",
        storage: "Коледино WB",
        seller: "OOO Вайлдберриз",
        image: "./images/Frame3853.jpg",
        price: "522",
        quantity: "2",
    },
    {
        id: 2,
        name: "Футболка UZcotton мужская",
        color: "белый",
        size: "",
        storage: "Коледино WB",
        seller: "OOO Вайлдберриз",
        image: "./images/Frame3853.jpg",
        price: "522",
        quantity: "0",
    },
]